-- Copy and paste this into Supabase SQL Editor and click "Run"

-- Create totes table with proper auto-incrementing ID
CREATE TABLE IF NOT EXISTS totes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  position TEXT NOT NULL,
  items JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE totes ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations (for development)
CREATE POLICY "Allow all operations on totes" ON totes
FOR ALL USING (true) WITH CHECK (true);

-- Enable real-time updates
ALTER PUBLICATION supabase_realtime ADD TABLE totes;