-- Copy and paste this into Supabase SQL Editor and click "Run"

-- Create totes table with proper auto-incrementing ID
CREATE TABLE IF NOT EXISTS totes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  position TEXT NOT NULL,
  items JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE totes ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if it exists and create new one
DROP POLICY IF EXISTS "Allow all operations on totes" ON totes;
CREATE POLICY "Allow all operations on totes" ON totes
FOR ALL USING (true) WITH CHECK (true);

-- Enable real-time updates (only if not already added)
DO $$ 
BEGIN 
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE totes;
  EXCEPTION 
    WHEN duplicate_object THEN 
      RAISE NOTICE 'Table totes is already in supabase_realtime publication';
  END;
END $$;